### ISSUE TITLE
Support for MangaFox?

### ISSUE THREAD

**Issue by janowskima** [poketo/poketo#38]
Hi,

would support for MangaFox be possible?

Best,
M

**Comment by rosszurowski** [comment]
I can look into supporting MangaFox. Tachiyomi (an Android-based manga reader) is able to support it, so Poketo should be able to do the same.

Are there particular series you're looking for on MangaFox that you could mention? Knowing them will:

1. Help me test support for MangaFox and,
2. Let me recommend alternative sources you could use in the meantime.

**Comment by janowskima** [comment]
Hey,

any of the top ratings will work; I know alternative sources and how to find them, just got used to Manga Fox, since I've been reading a lot of mangas there. Cheers for the message tho!
