### ISSUE TITLE
Bulk download?

### ISSUE THREAD

**Issue by pmwoodward3** [poketo/poketo#39]
Hey! Really fantastic work on this. I was wondering if there's a clean way to do a bulk download of a site, bulk meaning download everything. 

If anyone has any ideas i'd love to hear!

Thanks

**Comment by pmwoodward3** [comment]
I'm just a data hoarder and want to download pretty much want to download all the manga that exists haha.

I do have lists of all the urls from a few sites. Can you give me an example of how I would pass that through poketo? It's one url per line, so nothing crazy.

Thanks

**Comment by pmwoodward3** [comment]
Thanks for the quick reply! I was able to get that going on a my list of manga from mangadex, but it looks like i'm getting some weird characters in my folder names.

First one looks like this:

&quot;Aishiteru&quot;, Uso dakedo

Any idea what I can do to get around that? I guess I could just do a mass rename after the fact.

**Comment by rosszurowski** [comment]
Are those series from Mangadex?

I noticed a bug a few days ago (#37) where series from Mangadex has encoded characters in their titles. `&quot;` is HTML-speak for `"`. You might also see `&times;` and `&gt;` and others.

I should be able to push a fix for this later today, but until then, doing a batch rename would be easiest.

**Comment by rosszurowski** [comment]
I just pushed that fix in a new version of the poketo-cli, 0.0.7. If you upgrade, you should see those `&quot;` or other weird characters anymore.

I'm gonna close this issue since it sounds like you were able to achieve what you're after.
