### ISSUE TITLE
MangaHere & MerikaScans not working

### ISSUE THREAD

**Issue by SSebigo** [poketo/poketo#42]
I tried getting series information from MangaHere and MerikaScans with 

```javascript
poketo.getSeries().
```

For MangaHere, I tried this URL: [http://www.mangahere.cc/manga/dice_the_cube_that_changes_everything/](url) but got this error: 

> TypeError: Cannot read property 'trim' of undefined

For MerikaScans, I tried this URL: [https://merakiscans.com/details/their-color/](url) but got this error:

> NotFoundError: Not Found

Since I dont know how to contribute to look at those errors, I hope you'll found why they occur.
PS: I love this package!!!

**Comment by rosszurowski** [comment]
Thanks for reporting this.

Looks like Meraki recently updated their site, and I suspect MangaHere also recently made changes that broke something.

I should be able to publish a patch for this tomorrow.

**Comment by rosszurowski** [comment]
I pushed a fix for this in [0.6.11](https://github.com/poketo/poketo/releases), so these two sites should be working normally again. Let me know if you're still seeing issues.
