### ISSUE TITLE
Critical dependency errors

### ISSUE THREAD

**Issue by AniStream** [poketo/poketo#44]
Every time I try to import Poketo I get this error and my site won't work anymore. How should I go about fixing it?

![error](https://i.imgur.com/NTekZPw.png)

And if I go onto an actual page it will throw this error

![error](https://i.imgur.com/e79mFdH.png)

**Comment by rosszurowski** [comment]
From the webpack warnings, it looks you're trying to use poketo on a website.

Right now, this library is only built for Node. Web browsers restrict javascript's ability to load data across domains (eg. from domainone.com to domaintwo.com), which poketo needs to scrape sites, so running it on a server is the only option.

If you'd like, you can either run your own server that exposes the data you'd like. Or, you can use the version I'm hosting at [api.poketo.app](https://api.poketo.app).

**Comment by Deterio** [comment]
Yeah, I was trying to run it on the stie, I already looked at the API and it's pretty neat, it would've just been cool if I were able to use the actual package

**Comment by rosszurowski** [comment]
Yeah. I've considered having a separate build for browsers that, behind the scenes, just makes calls to api.poketo.app, but haven't gotten around to it yet.

Anyways, if you end up using the API let me know if you run into any troubles. I made Poketo to be built on top of, so I'm down to help work though any issues.
